### ISSUE TITLE
Add a "pipe" character between clock events on main page

### ISSUE THREAD

**Issue by diegosurita** [wesleynepo/hmtiw-senior#6]
I'd like to suggest adding a "pipe" character between the clock events listed on main page, as example bellow.

![image](https://user-images.githubusercontent.com/3666378/166744223-ba59bcb4-5016-4b12-845f-cf5afa4249d3.png)

**Comment by wesleynepo** [comment]
Sure, we can match the color of pipes with the horizontal dividers like this. 
![image](https://user-images.githubusercontent.com/50495587/166848189-ad229203-9880-4042-91c9-bb9fb660bece.png)
But there's a catch, the mobile layout behave different so we might need to change how the timestamps come from context, today they come as a string.
![image](https://user-images.githubusercontent.com/50495587/166848736-66ad58f5-5f17-42a2-8ae5-29accff687cd.png)
And use something like a Stack from Chakra UI, handle the direction with breakpoints, and the pipes inserted by the divider prop from Stack, hiding him when mobile.

**Comment by diegosurita** [comment]
Nice!
I can work on this changes.
